CREATE TABLE "ToDoUser"(
id SERIAL PRIMARY KEY,
"Telegram_UserId" INTEGER NOT NULL,
"Telegram_UserName" VARCHAR NOT NULL,
"Registered_At" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ToDoList"(
id SERIAL PRIMARY KEY,
"ListName" VARCHAR NOT NULL,
"CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
"UserId" INTEGER REFERENCES "ToDoUser"(id)
);

CREATE TABLE "ToDoItem"(
id SERIAL PRIMARY KEY,
"ItemName" VARCHAR NOT NULL,
"CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
"ItemState" INTEGER NOT NULL,
"DeadLine" TIMESTAMP NOT NULL,
"StateChangedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
"UserId" INTEGER REFERENCES "ToDoUser"(id),
"ToDoList" INTEGER REFERENCES "ToDoList"(Id)
);

CREATE INDEX "idx_ToDoList_userid" ON "ToDoList"("UserId");
CREATE INDEX "idx_ToDoItem_userid" ON "ToDoItem"("UserId");
CREATE INDEX "idx_ToDoItem_ToDoList" ON "ToDoItem"("ToDoList");
CREATE UNIQUE INDEX "idx_ToDoUser_telegramuserid" ON "ToDoUser"("Telegram_UserId");