CREATE TABLE To_Do_User(
User_Id SERIAL PRIMARY KEY,
Telegram_UserId INTEGER NOT NULL,
Telegram_UserName VARCHAR NOT NULL,
Registered_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE To_Do_List(
id SERIAL PRIMARY KEY,
List_Name VARCHAR NOT NULL,
Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
User_Id INTEGER REFERENCES To_Do_User(User_Id) ON DELETE CASCADE
);

CREATE TABLE To_Do_Item(
id SERIAL PRIMARY KEY,
Item_Name VARCHAR NOT NULL,
Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Item_State INTEGER NOT NULL,
DeadLine TIMESTAMP NOT NULL,
State_Changed_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
User_Id INTEGER REFERENCES To_Do_User(User_Id) ON DELETE CASCADE,
To_Do_List INTEGER REFERENCES To_Do_List(Id) On DELETE CASCADE
);

CREATE INDEX idx_todolist_userid ON To_Do_List(User_Id);
CREATE INDEX idx_todoitem_userid ON To_Do_Item(User_Id);
CREATE INDEX idx_todoitem_todolist ON To_Do_Item(To_Do_List);
CREATE UNIQUE INDEX idx_todouser_telegramuserid ON To_Do_User(Telegram_UserId);